_mcreator_map_template: "@NAMEFeature.configuredFeature()"
_default: Features.OAK
acacia: Features.ACACIA
bamboo_no_podzol: Features.BAMBOO_LIGHT
bamboo_some_podzol: Features.BAMBOO
bamboo_vegetation: Features.BAMBOO_VEGETATION
basalt_blobs: Features.BASALT_BLOBS
basalt_pillar: Features.BASALT_PILLAR
birch: Features.BIRCH
birch_bees_0002: Features.BIRCH_BEES_0002
birch_bees_002: Features.BIRCH_BEES_002
birch_bees_005: Features.BIRCH_BEES_005
birch_tall: Features.BIRCH_TALL
blackstone_blobs: Features.BLACKSTONE_BLOBS
blue_ice: Features.BLUE_ICE
bonus_chest: Features.BONUS_CHEST
chorus_plant: Features.CHORUS_PLANT
crimson_forest_vegetation: Features.CRIMSON_FOREST_VEGETATION
crimson_forest_vegetation_bonemeal: Features.CRIMSON_FOREST_VEGETATION
crimson_fungus: Features.CRIMSON_FUNGI
crimson_fungus_planted: Features.CRIMSON_FUNGI_PLANTED
dark_forest_vegetation: Features.DARK_FOREST_VEGETATION_BROWN
dark_oak: Features.DARK_OAK
delta: Features.DELTA
desert_well: Features.DESERT_WELL
disk_clay: Features.DISK_CLAY
disk_gravel: Features.DISK_GRAVEL
disk_sand: Features.DISK_SAND
end_gateway_delayed: Features.END_GATEWAY_DELAYED
end_gateway_return: Features.END_GATEWAY
end_island: Features.END_ISLAND
end_spike: Features.END_SPIKE
fancy_oak: Features.FANCY_OAK
fancy_oak_bees: Features.FANCY_OAK_BEES_0002
fancy_oak_bees_0002: Features.FANCY_OAK_BEES_0002
fancy_oak_bees_002: Features.FANCY_OAK_BEES_002
fancy_oak_bees_005: Features.FANCY_OAK_BEES_005
flower_default: Features.FLOWER_DEFAULT
flower_flower_forest: Features.FLOWER_FOREST
flower_meadow: Features.FLOWER_PLAIN
flower_plain: Features.FLOWER_PLAIN
flower_swamp: Features.FLOWER_SWAMP
forest_flowers: Features.FLOWER_FOREST
forest_rock: Features.FOREST_ROCK
fossil_coal: Features.FOSSIL
fossil_diamonds: Features.FOSSIL
freeze_top_layer: Features.FREEZE_TOP_LAYER
glowstone_extra: Features.GLOWSTONE_EXTRA
huge_brown_mushroom: Features.HUGE_BROWN_MUSHROOM
huge_red_mushroom: Features.HUGE_RED_MUSHROOM
ice_patch: Features.ICE_PATCH
ice_spike: Features.ICE_SPIKE
iceberg_blue: Features.ICEBERG_BLUE
iceberg_packed: Features.ICEBERG_PACKED
jungle_bush: Features.JUNGLE_BUSH
jungle_tree: Features.JUNGLE_TREE
jungle_tree_no_vine: Features.JUNGLE_TREE_NO_VINE
kelp: Features.KELP_WARM
lake_lava: Features.LAKE_LAVA
large_basalt_columns: Features.LARGE_BASALT_COLUMNS
meadow_trees: Features.OAK
mega_jungle_tree: Features.MEGA_JUNGLE_TREE
mega_pine: Features.MEGA_PINE
mega_spruce: Features.MEGA_SPRUCE
monster_room: Features.MONSTER_ROOM
mushroom_island_vegetation: Features.MUSHROOM_FIELD_VEGETATION
nether_sprouts: Features.NETHER_SPROUTS
nether_sprouts_bonemeal: Features.NETHER_SPROUTS
oak: Features.OAK
oak_bees_0002: Features.OAK_BEES_0002
oak_bees_002: Features.OAK_BEES_002
oak_bees_005: Features.OAK_BEES_005
ore_ancient_debris_large: Features.ORE_DEBRIS_LARGE
ore_ancient_debris_small: Features.ORE_DEBRIS_SMALL
ore_andesite: Features.ORE_ANDESITE
ore_blackstone: Features.ORE_BLACKSTONE
ore_coal: Features.ORE_COAL
ore_coal_buried: Features.ORE_COAL
ore_diamond_buried: Features.ORE_DIAMOND
ore_diamond_large: Features.ORE_DIAMOND
ore_diamond_medium: Features.ORE_DIAMOND
ore_diamond_small: Features.ORE_DIAMOND
ore_diorite: Features.ORE_DIORITE
ore_dirt: Features.ORE_DIRT
ore_emerald: Features.ORE_EMERALD
ore_gold: Features.ORE_GOLD
ore_gold_buried: Features.ORE_GOLD_EXTRA
ore_granite: Features.ORE_GRANITE
ore_gravel: Features.ORE_GRAVEL
ore_gravel_nether: Features.ORE_GRAVEL_NETHER
ore_infested: Features.ORE_INFESTED
ore_iron: Features.ORE_IRON
ore_iron_small: Features.ORE_IRON
ore_lapis: Features.ORE_LAPIS
ore_lapis_buried: Features.ORE_LAPIS
ore_magma: Features.ORE_MAGMA
ore_nether_gold: Features.ORE_GOLD_NETHER
ore_quartz: Features.ORE_QUARTZ_NETHER
ore_redstone: Features.ORE_REDSTONE
ore_soul_sand: Features.ORE_SOUL_SAND
patch_berry_bush: Features.PATCH_BERRY_BUSH
patch_brown_mushroom: Features.PATCH_BROWN_MUSHROOM
patch_cactus: Features.PATCH_CACTUS
patch_crimson_roots: Features.PATCH_CRIMSON_ROOTS
patch_dead_bush: Features.PATCH_DEAD_BUSH
patch_fire: Features.PATCH_FIRE
patch_grass: Features.PATCH_GRASS_NORMAL
patch_grass_jungle: Features.PATCH_GRASS_JUNGLE
patch_large_fern: Features.PATCH_LARGE_FERN
patch_melon: Features.PATCH_MELON
patch_pumpkin: Features.PATCH_PUMPKIN
patch_red_mushroom: Features.PATCH_RED_MUSHROOM
patch_soul_fire: Features.PATCH_SOUL_FIRE
patch_sugar_cane: Features.PATCH_SUGAR_CANE
patch_sunflower: Features.PATCH_SUNFLOWER
patch_taiga_grass: Features.PATCH_TAIGA_GRASS
patch_tall_grass: Features.PATCH_TALL_GRASS
patch_waterlily: Features.PATCH_WATERLILLY
pile_hay: Features.PILE_HAY
pile_ice: Features.PILE_ICE
pile_melon: Features.PILE_MELON
pile_pumpkin: Features.PILE_PUMPKIN
pile_snow: Features.PILE_SNOW
pine: Features.PINE
sea_pickle: Features.SEA_PICKLE
seagrass_mid: Features.SEAGRASS_SIMPLE
seagrass_short: Features.SEAGRASS_RIVER
seagrass_slightly_less_short: Features.SEAGRASS_NORMAL
seagrass_tall: Features.SEAGRASS_DEEP
small_basalt_columns: Features.SMALL_BASALT_COLUMNS
spring_lava_frozen: Features.SPRING_LAVA
spring_lava_nether: Features.SPRING_OPEN
spring_lava_overworld: Features.SPRING_LAVA
spring_nether_closed: Features.SPRING_CLOSED
spring_nether_open: Features.SPRING_OPEN
spring_water: Features.SPRING_WATER
spruce: Features.SPRUCE
super_birch_bees: Features.SUPER_BIRCH_BEES_0002
super_birch_bees_0002: Features.SUPER_BIRCH_BEES_0002
swamp_oak: Features.SWAMP_TREE
trees_birch_and_oak: Features.BIRCH_OTHER
trees_flower_forest: Features.FOREST_FLOWER_TREES
trees_jungle: Features.TREES_JUNGLE
trees_old_growth_pine_taiga: Features.TREES_GIANT_SPRUCE
trees_old_growth_spruce_taiga: Features.TREES_GIANT
trees_plains: Features.PLAIN_VEGETATION
trees_savanna: Features.TREES_SAVANNA
trees_sparse_jungle: Features.TREES_JUNGLE_EDGE
trees_taiga: Features.TAIGA_VEGETATION
trees_water: Features.TREES_WATER
trees_windswept_hills: Features.TREES_MOUNTAIN
twisting_vines: Features.TWISTING_VINES
twisting_vines_bonemeal: Features.TWISTING_VINES
underwater_magma: Features.ORE_MAGMA
vines: Features.VINES
void_start_platform: Features.VOID_START_PLATFORM
warm_ocean_vegetation: Features.WARM_OCEAN_VEGETATION
warped_forest_vegetation: Features.WARPED_FOREST_VEGETATION
warped_forest_vegetation_bonemeal: Features.WARPED_FOREST_VEGETATION
warped_fungus: Features.WARPED_FUNGI
warped_fungus_planted: Features.WARPED_FUNGI_PLANTED
weeping_vines: Features.WEEPING_VINES