_mcreator_map_template:
  - "@modid:@registryname"
  - "@NAMEFeature.configuredFeature()"
  - "@NAMEFeature"
_default:
  - oak
  - Features.OAK
  - TreeConfiguration
acacia:
  - acacia
  - Features.ACACIA
  - TreeConfiguration
amethyst_geode:
  - amethyst_geode
  - Features.AMETHYST_GEODE
  - GeodeConfiguration
azalea_tree:
  - azalea_tree
  - Features.AZALEA_TREE
  - TreeConfiguration
bamboo_no_podzol:
  - bamboo_light
  - Features.BAMBOO_LIGHT
  - ProbabilityFeatureConfiguration
bamboo_some_podzol:
  - bamboo
  - Features.BAMBOO
  - ProbabilityFeatureConfiguration
bamboo_vegetation:
  - bamboo_vegetation
  - Features.BAMBOO_VEGETATION
  - RandomFeatureConfiguration
basalt_blobs:
  - basalt_blobs
  - Features.BASALT_BLOBS
  - ReplaceSphereConfiguration
basalt_pillar:
  - basalt_pillar
  - Features.BASALT_PILLAR
  - ColumnFeatureConfiguration
birch:
  - birch
  - Features.BIRCH
  - TreeConfiguration
birch_bees_0002:
  - birch_bees_0002
  - Features.BIRCH_BEES_0002
  - TreeConfiguration
birch_bees_002:
  - birch_bees_002
  - Features.BIRCH_BEES_002
  - TreeConfiguration
birch_bees_005:
  - birch_bees_005
  - Features.BIRCH_BEES_005
  - TreeConfiguration
birch_tall:
  - birch_tall
  - Features.BIRCH_TALL
  - RandomFeatureConfiguration
blackstone_blobs:
  - blackstone_blobs
  - Features.BLACKSTONE_BLOBS
  - ReplaceSphereConfiguration
blue_ice:
  - blue_ice
  - Features.BLUE_ICE
  - NoneFeatureConfiguration
bonus_chest:
  - bonus_chest
  - Features.BONUS_CHEST
  - NoneFeatureConfiguration
cave_vine:
  - cave_vine
  - Features.CAVE_VINE
  - BlockColumnConfiguration
cave_vine_in_moss:
  - cave_vine_in_moss
  - Features.CAVE_VINE_IN_MOSS
  - BlockColumnConfiguration
chorus_plant:
  - chorus_plant
  - Features.CHORUS_PLANT
  - NoneFeatureConfiguration
clay_pool_with_dripleaves:
  - clay_pool_with_dripleaves
  - Features.CLAY_POOL_WITH_DRIPLEAVES
  - VegetationPatchConfiguration
clay_with_dripleaves:
  - clay_with_dripleaves
  - Features.CLAY_WITH_DRIPLEAVES
  - VegetationPatchConfiguration
crimson_forest_vegetation:
  - crimson_forest_vegetation
  - Features.CRIMSON_FOREST_VEGETATION
  - NetherForestVegetationConfig
crimson_forest_vegetation_bonemeal:
  - crimson_forest_vegetation
  - Features.CRIMSON_FOREST_VEGETATION
  - NetherForestVegetationConfig
crimson_fungus:
  - crimson_fungi
  - Features.CRIMSON_FUNGI
  - HugeFungusConfiguration
crimson_fungus_planted:
  - crimson_fungi_planted
  - Features.CRIMSON_FUNGI_PLANTED
  - HugeFungusConfiguration
dark_forest_vegetation:
  - dark_forest_vegetation
  - Features.DARK_FOREST_VEGETATION_BROWN
  - RandomFeatureConfiguration
dark_oak:
  - dark_oak
  - Features.DARK_OAK
  - TreeConfiguration
delta:
  - delta
  - Features.DELTA
  - DeltaFeatureConfiguration
desert_well:
  - desert_well
  - Features.WELL
  - NoneFeatureConfiguration
disk_clay:
  - disk_clay
  - Features.DISK_CLAY
  - DiskConfiguration
disk_grass:
  - patch_grass_plain
  - Features.PATCH_GRASS_PLAIN
  - RandomPatchConfiguration
disk_gravel:
  - disk_gravel
  - Features.DISK_GRAVEL
  - DiskConfiguration
disk_sand:
  - disk_sand
  - Features.DISK_SAND
  - DiskConfiguration
dripleaf:
  - dripleaf
  - Features.DRIPLEAF
  - SimpleRandomFeatureConfiguration
dripstone_cluster:
  - dripstone_cluster
  - Features.DRIPSTONE_CLUSTER_FEATURE
  - DripstoneClusterConfiguration
end_gateway_delayed:
  - end_gateway_delayed
  - Features.END_GATEWAY_DELAYED
  - EndGatewayConfiguration
end_gateway_return:
  - end_gateway_delayed
  - Features.END_GATEWAY_DELAYED
  - EndGatewayConfiguration
end_island:
  - end_island
  - Features.END_ISLAND
  - NoneFeatureConfiguration
end_spike:
  - end_spike
  - Features.END_SPIKE
  - SpikeConfiguration
fancy_oak:
  - fancy_oak
  - Features.FANCY_OAK
  - TreeConfiguration
fancy_oak_bees:
  - fancy_oak_bees_0002
  - Features.FANCY_OAK_BEES_0002
  - TreeConfiguration
fancy_oak_bees_0002:
  - fancy_oak_bees_0002
  - Features.FANCY_OAK_BEES_0002
  - TreeConfiguration
fancy_oak_bees_002:
  - fancy_oak_bees_002
  - Features.FANCY_OAK_BEES_002
  - TreeConfiguration
fancy_oak_bees_005:
  - fancy_oak_bees_005
  - Features.FANCY_OAK_BEES_005
  - TreeConfiguration
flower_default:
  - flower_default
  - Features.FLOWER_DEFAULT
  - RandomPatchConfiguration
flower_flower_forest:
  - forest_flower_trees
  - Features.FOREST_FLOWER_TREES
  - RandomFeatureConfiguration
flower_meadow:
  - forest_flower_trees
  - Features.FOREST_FLOWER_TREES
  - RandomFeatureConfiguration
flower_plain:
  - flower_plain
  - Features.FLOWER_PLAIN
  - NoiseThresholdProviderConfiguration
flower_swamp:
  - flower_swamp
  - Features.FLOWER_SWAMP
  - RandomPatchConfiguration
forest_flowers:
  - forest_flower_vegetation_common
  - Features.FOREST_FLOWER_VEGETATION_COMMON
  - SimpleRandomFeatureConfiguration
forest_rock:
  - forest_rock
  - Features.FOREST_ROCK
  - BlockStateConfiguration
fossil_coal:
  - prototype_fossil_upper
  - Features.PROTOTYPE_FOSSIL_UPPER
  - FossilFeatureConfiguration
fossil_diamonds:
  - prototype_fossil_lower
  - Features.PROTOTYPE_FOSSIL_LOWER
  - FossilFeatureConfiguration
freeze_top_layer:
  - freeze_top_layer
  - Features.FREEZE_TOP_LAYER
  - NoneFeatureConfiguration
glow_lichen:
  - glow_lichen
  - Features.GLOW_LICHEN
  - GlowLichenConfiguration
glowstone_extra:
  - glowstone_extra
  - Features.GLOWSTONE_EXTRA
  - NoneFeatureConfiguration
huge_brown_mushroom:
  - huge_brown_mushroom
  - Features.HUGE_BROWN_MUSHROOM
  - HugeMushroomFeatureConfiguration
huge_red_mushroom:
  - huge_red_mushroom
  - Features.HUGE_RED_MUSHROOM
  - HugeMushroomFeatureConfiguration
ice_patch:
  - ice_patch
  - Features.ICE_PATCH
  - DiskConfiguration
ice_spike:
  - ice_spike
  - Features.ICE_SPIKE
  - NoneFeatureConfiguration
iceberg_blue:
  - iceberg_blue
  - Features.ICEBERG_BLUE
  - BlockStateConfiguration
iceberg_packed:
  - iceberg_packed
  - Features.ICEBERG_PACKED
  - BlockStateConfiguration
jungle_bush:
  - jungle_bush
  - Features.JUNGLE_BUSH
  - TreeConfiguration
jungle_tree:
  - jungle_tree
  - Features.JUNGLE_TREE
  - TreeConfiguration
jungle_tree_no_vine:
  - jungle_tree_no_vine
  - Features.JUNGLE_TREE_NO_VINE
  - TreeConfiguration
kelp:
  - kelp_warm
  - Features.KELP_WARM
  - NoneFeatureConfiguration
lake_lava:
  - lake_lava
  - Features.LAKE_LAVA
  - LakeFeature.Configuration
large_basalt_columns:
  - large_basalt_columns
  - Features.LARGE_BASALT_COLUMNS
  - ColumnFeatureConfiguration
large_dripstone:
  - large_dripstone
  - Features.LARGE_DRIPSTONE_FEATURE
  - LargeDripstoneConfiguration
lush_caves_clay:
  - lush_caves_clay
  - Features.LUSH_CAVES_CLAY
  - RandomBooleanFeatureConfiguration
mega_jungle_tree:
  - mega_jungle_tree
  - Features.MEGA_JUNGLE_TREE
  - TreeConfiguration
mega_pine:
  - mega_pine
  - Features.MEGA_PINE
  - TreeConfiguration
mega_spruce:
  - mega_spruce
  - Features.MEGA_SPRUCE
  - TreeConfiguration
monster_room:
  - monster_room
  - Features.MONSTER_ROOM
  - NoneFeatureConfiguration
moss_patch:
  - moss_patch
  - Features.MOSS_PATCH
  - VegetationPatchConfiguration
moss_patch_bonemeal:
  - moss_patch_bonemeal
  - Features.MOSS_PATCH_BONEMEAL
  - VegetationPatchConfiguration
moss_patch_ceiling:
  - moss_patch_ceiling
  - Features.MOSS_PATCH_CEILING
  - VegetationPatchConfiguration
moss_vegetation:
  - moss_vegetation
  - Features.MOSS_VEGETATION
  - SimpleBlockConfiguration
mushroom_island_vegetation:
  - mushroom_field_vegetation
  - Features.MUSHROOM_FIELD_VEGETATION
  - RandomBooleanFeatureConfiguration
nether_sprouts:
  - nether_sprouts
  - Features.NETHER_SPROUTS
  - NetherForestVegetationConfig
nether_sprouts_bonemeal:
  - nether_sprouts
  - Features.NETHER_SPROUTS
  - NetherForestVegetationConfig
oak:
  - oak
  - Features.OAK
  - TreeConfiguration
oak_bees_0002:
  - oak_bees_0002
  - Features.OAK_BEES_0002
  - TreeConfiguration
oak_bees_002:
  - oak_bees_002
  - Features.OAK_BEES_002
  - TreeConfiguration
oak_bees_005:
  - oak_bees_005
  - Features.OAK_BEES_005
  - TreeConfiguration
ore_ancient_debris_large:
  - ore_debris_large
  - Features.ORE_DEBRIS_LARGE
  - OreConfiguration
ore_ancient_debris_small:
  - ore_debris_small
  - Features.ORE_DEBRIS_SMALL
  - OreConfiguration
ore_andesite:
  - ore_andesite
  - Features.ORE_ANDESITE
  - OreConfiguration
ore_blackstone:
  - ore_blackstone
  - Features.ORE_BLACKSTONE
  - OreConfiguration
ore_clay:
  - ore_clay
  - Features.ORE_CLAY
  - OreConfiguration
ore_coal:
  - ore_coal
  - Features.ORE_COAL
  - OreConfiguration
ore_coal_buried:
  - prototype_ore_coal_lower
  - Features.PROTOTYPE_ORE_COAL_LOWER
  - OreConfiguration
ore_copper_large:
  - prototype_ore_copper
  - Features.PROTOTYPE_ORE_COPPER
  - OreConfiguration
ore_copper_small:
  - ore_copper
  - Features.ORE_COPPER
  - OreConfiguration
ore_diamond_buried:
  - ore_diamond
  - Features.ORE_DIAMOND
  - OreConfiguration
ore_diamond_large:
  - prototype_ore_diamond_large
  - Features.PROTOTYPE_ORE_DIAMOND_LARGE
  - OreConfiguration
ore_diamond_small:
  - prototype_ore_diamond
  - Features.PROTOTYPE_ORE_DIAMOND
  - OreConfiguration
ore_diorite:
  - ore_diorite
  - Features.ORE_DIORITE
  - OreConfiguration
ore_dirt:
  - ore_dirt
  - Features.ORE_DIRT
  - OreConfiguration
ore_emerald:
  - ore_emerald
  - Features.ORE_EMERALD
  - OreConfiguration
ore_gold:
  - ore_gold
  - Features.ORE_GOLD
  - OreConfiguration
ore_gold_buried:
  - prototype_ore_gold
  - Features.PROTOTYPE_ORE_GOLD
  - OreConfiguration
ore_granite:
  - ore_granite
  - Features.ORE_GRANITE
  - OreConfiguration
ore_gravel:
  - ore_gravel
  - Features.ORE_GRAVEL
  - OreConfiguration
ore_gravel_nether:
  - ore_gravel_nether
  - Features.ORE_GRAVEL_NETHER
  - OreConfiguration
ore_infested:
  - ore_infested
  - Features.ORE_INFESTED
  - OreConfiguration
ore_iron:
  - ore_iron
  - Features.ORE_IRON
  - OreConfiguration
ore_iron_small:
  - prototype_ore_iron_small
  - Features.PROTOTYPE_ORE_IRON_SMALL
  - OreConfiguration
ore_lapis:
  - ore_lapis
  - Features.ORE_LAPIS
  - OreConfiguration
ore_lapis_buried:
  - prototype_ore_lapis_buried
  - Features.PROTOTYPE_ORE_LAPIS_BURIED
  - OreConfiguration
ore_magma:
  - ore_magma
  - Features.ORE_MAGMA
  - OreConfiguration
ore_nether_gold:
  - ore_gold_nether
  - Features.ORE_GOLD_NETHER
  - OreConfiguration
ore_quartz:
  - ore_quartz_nether
  - Features.ORE_QUARTZ_NETHER
  - OreConfiguration
ore_redstone:
  - ore_redstone
  - Features.ORE_REDSTONE
  - OreConfiguration
ore_soul_sand:
  - ore_soul_sand
  - Features.ORE_SOUL_SAND
  - OreConfiguration
ore_tuff:
  - ore_tuff
  - Features.ORE_TUFF
  - OreConfiguration
patch_berry_bush:
  - patch_berry_bush
  - Features.PATCH_BERRY_BUSH
  - RandomPatchConfiguration
patch_brown_mushroom:
  - patch_brown_mushroom
  - Features.PATCH_BROWN_MUSHROOM
  - RandomPatchConfiguration
patch_cactus:
  - patch_cactus
  - Features.PATCH_CACTUS
  - RandomPatchConfiguration
patch_crimson_roots:
  - patch_crimson_roots
  - Features.PATCH_CRIMSON_ROOTS
  - RandomPatchConfiguration
patch_dead_bush:
  - patch_dead_bush
  - Features.PATCH_DEAD_BUSH
  - RandomPatchConfiguration
patch_fire:
  - patch_fire
  - Features.PATCH_FIRE
  - RandomPatchConfiguration
patch_grass:
  - patch_grass_plain
  - Features.PATCH_GRASS_PLAIN
  - RandomPatchConfiguration
patch_grass_jungle:
  - patch_grass_jungle
  - Features.PATCH_GRASS_JUNGLE
  - RandomPatchConfiguration
patch_large_fern:
  - patch_large_fern
  - Features.PATCH_LARGE_FERN
  - RandomPatchConfiguration
patch_melon:
  - patch_melon
  - Features.PATCH_MELON
  - RandomPatchConfiguration
patch_pumpkin:
  - patch_pumpkin
  - Features.PATCH_PUMPKIN
  - RandomPatchConfiguration
patch_red_mushroom:
  - patch_red_mushroom
  - Features.PATCH_RED_MUSHROOM
  - RandomPatchConfiguration
patch_soul_fire:
  - patch_soul_fire
  - Features.PATCH_SOUL_FIRE
  - RandomPatchConfiguration
patch_sugar_cane:
  - patch_sugar_cane
  - Features.PATCH_SUGAR_CANE
  - RandomPatchConfiguration
patch_sunflower:
  - patch_sunflower
  - Features.PATCH_SUNFLOWER
  - RandomPatchConfiguration
patch_taiga_grass:
  - patch_taiga_grass
  - Features.PATCH_TAIGA_GRASS
  - RandomPatchConfiguration
patch_tall_grass:
  - patch_tall_grass
  - Features.PATCH_TALL_GRASS
  - RandomPatchConfiguration
patch_waterlily:
  - patch_waterlily
  - Features.PATCH_WATERLILLY
  - RandomPatchConfiguration
pile_hay:
  - pile_hay
  - Features.PILE_HAY
  - BlockPileConfiguration
pile_ice:
  - pile_ice
  - Features.PILE_ICE
  - BlockPileConfiguration
pile_melon:
  - pile_melon
  - Features.PILE_MELON
  - BlockPileConfiguration
pile_pumpkin:
  - pile_pumpkin
  - Features.PILE_PUMPKIN
  - BlockPileConfiguration
pile_snow:
  - pile_snow
  - Features.PILE_SNOW
  - BlockPileConfiguration
pine:
  - pine
  - Features.PINE
  - TreeConfiguration
pointed_dripstone:
  - large_dripstone
  - Features.LARGE_DRIPSTONE_FEATURE
  - LargeDripstoneConfiguration
rooted_azalea_tree:
  - rooted_azalea_trees
  - Features.ROOTED_AZALEA_TREES
  - RootSystemConfiguration
sea_pickle:
  - sea_pickle
  - Features.SEA_PICKLE
  - CountConfiguration
seagrass_mid:
  - seagrass_simple
  - Features.SEAGRASS_SIMPLE
  - SimpleBlockConfiguration
seagrass_short:
  - seagrass_simple
  - Features.SEAGRASS_SIMPLE
  - SimpleBlockConfiguration
seagrass_slightly_less_short:
  - seagrass_simple
  - Features.SEAGRASS_SIMPLE
  - SimpleBlockConfiguration
seagrass_tall:
  - seagrass_deep
  - Features.SEAGRASS_DEEP
  - ProbabilityFeatureConfiguration
small_basalt_columns:
  - small_basalt_columns
  - Features.SMALL_BASALT_COLUMNS
  - ColumnFeatureConfiguration
spore_blossom:
  - spore_blossom
  - Features.SPORE_BLOSSOM_FEATURE
  - SimpleBlockConfiguration
spring_lava_frozen:
  - spring_lava
  - Features.SPRING_LAVA
  - SpringConfiguration
spring_lava_nether:
  - spring_lava
  - Features.SPRING_LAVA
  - SpringConfiguration
spring_lava_overworld:
  - spring_lava
  - Features.SPRING_LAVA
  - SpringConfiguration
spring_nether_closed:
  - spring_lava
  - Features.SPRING_LAVA
  - SpringConfiguration
spring_nether_open:
  - spring_lava
  - Features.SPRING_LAVA
  - SpringConfiguration
spring_water:
  - spring_water
  - Features.SPRING_WATER
  - SpringConfiguration
spruce:
  - spruce
  - Features.SPRUCE
  - TreeConfiguration
super_birch_bees:
  - spruce
  - Features.SPRUCE
  - TreeConfiguration
super_birch_bees_0002:
  - super_birch_bees_0002
  - Features.SUPER_BIRCH_BEES_0002
  - TreeConfiguration
swamp_oak:
  - swamp_oak
  - Features.SWAMP_OAK
  - TreeConfiguration
trees_birch_and_oak:
  - trees_birch
  - Features.BIRCH_OTHER
  - RandomFeatureConfiguration
trees_flower_forest:
  - forest_flower_trees
  - Features.FOREST_FLOWER_TREES
  - RandomFeatureConfiguration
trees_jungle:
  - trees_jungle
  - Features.TREES_JUNGLE
  - RandomFeatureConfiguration
trees_old_growth_pine_taiga:
  - mega_pine
  - Features.MEGA_PINE
  - TreeConfiguration
trees_old_growth_spruce_taiga:
  - mega_spruce
  - Features.MEGA_SPRUCE
  - TreeConfiguration
trees_plains:
  - plain_vegetation
  - Features.PLAIN_VEGETATION
  - RandomFeatureConfiguration
trees_savanna:
  - trees_water
  - Features.TREES_WATER
  - RandomFeatureConfiguration
trees_sparse_jungle:
  - trees_jungle_edge
  - Features.TREES_JUNGLE_EDGE
  - RandomFeatureConfiguration
trees_taiga:
  - taiga_vegetation
  - Features.TAIGA_VEGETATION
  - RandomFeatureConfiguration
trees_water:
  - trees_water
  - Features.TREES_WATER
  - RandomFeatureConfiguration
trees_windswept_hills:
  - trees_mountain
  - Features.TREES_MOUNTAIN
  - RandomFeatureConfiguration
twisting_vines:
  - twisting_vines
  - Features.TWISTING_VINES
  - TwistingVinesConfig
twisting_vines_bonemeal:
  - twisting_vines
  - Features.TWISTING_VINES
  - TwistingVinesConfig
underwater_magma:
  - prototype_underwater_magma
  - Features.PROTOTYPE_UNDERWATER_MAGMA
  - UnderwaterMagmaConfiguration
vines:
  - vines
  - Features.VINES
  - NoneFeatureConfiguration
void_start_platform:
  - void_start_platform
  - Features.VOID_START_PLATFORM
  - NoneFeatureConfiguration
warm_ocean_vegetation:
  - warm_ocean_vegetation
  - Features.WARM_OCEAN_VEGETATION
  - SimpleRandomFeatureConfiguration
warped_forest_vegetation:
  - warped_forest_vegetation
  - Features.WARPED_FOREST_VEGETATION
  - NetherForestVegetationConfig
warped_forest_vegetation_bonemeal:
  - warped_forest_vegetation
  - Features.WARPED_FOREST_VEGETATION
  - NetherForestVegetationConfig
warped_fungus:
  - warped_fungi
  - Features.WARPED_FUNGI
  - HugeFungusConfiguration
warped_fungus_planted:
  - warped_fungi_planted
  - Features.WARPED_FUNGI_PLANTED
  - HugeFungusConfiguration
weeping_vines:
  - weeping_vines
  - Features.WEEPING_VINES
  - NoneFeatureConfiguration