_mcreator_map_template: "@NAMEFeature.configuredFeature()"
_default: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.OAK_TREE_CONFIG)"
acacia: "Feature.ACACIA_TREE.withConfiguration(DefaultBiomeFeatures.ACACIA_TREE_CONFIG)"
bamboo_no_podzol: "Feature.BAMBOO.withConfiguration(new ProbabilityConfig(0.0F))"
bamboo_some_podzol: "Feature.BAMBOO.withConfiguration(new ProbabilityConfig(0.2F))"
birch: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.BIRCH_TREE_CONFIG)"
birch_bees_0002: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.field_230129_h_)"
birch_bees_002: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.field_230135_r_)"
birch_bees_005: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.field_230136_s_)"
birch_tall: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.field_230130_i_)"
blue_ice: "Feature.BLUE_ICE.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
bonus_chest: "Feature.BONUS_CHEST.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
chorus_plant: "Feature.CHORUS_PLANT.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
dark_oak: "Feature.DARK_OAK_TREE.withConfiguration(DefaultBiomeFeatures.DARK_OAK_TREE_CONFIG)"
desert_well: "Feature.DESERT_WELL.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
disk_clay: "Feature.DISK.withConfiguration(new SphereReplaceConfig(Blocks.CLAY.getDefaultState(), 4, 1, Lists.newArrayList(Blocks.DIRT.getDefaultState(), Blocks.CLAY.getDefaultState())))"
disk_gravel: "Feature.DISK.withConfiguration(new SphereReplaceConfig(Blocks.GRAVEL.getDefaultState(), 6, 2, Lists.newArrayList(Blocks.DIRT.getDefaultState(), Blocks.GRASS_BLOCK.getDefaultState())))"
disk_sand: "Feature.DISK.withConfiguration(new SphereReplaceConfig(Blocks.SAND.getDefaultState(), 7, 2, Lists.newArrayList(Blocks.DIRT.getDefaultState(), Blocks.GRASS_BLOCK.getDefaultState())))"
end_gateway_delayed: "Feature.END_GATEWAY.withConfiguration(EndGatewayConfig.func_214702_a())"
end_gateway_return: "Feature.END_GATEWAY.withConfiguration(EndGatewayConfig.func_214702_a())"
end_island: "Feature.END_ISLAND.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
end_spike: "Feature.END_SPIKE.withConfiguration(new EndSpikeFeatureConfig(false, ImmutableList.of(), Optional.empty()))"
fancy_oak: "Feature.FANCY_TREE.withConfiguration(DefaultBiomeFeatures.FANCY_TREE_CONFIG)"
fancy_oak_bees_0002: "Feature.FANCY_TREE.withConfiguration(DefaultBiomeFeatures.field_230131_m_)"
fancy_oak_bees_002: "Feature.FANCY_TREE.withConfiguration(DefaultBiomeFeatures.field_230134_q_)"
fancy_oak_bees_005: "Feature.FANCY_TREE.withConfiguration(DefaultBiomeFeatures.FANCY_TREE_WITH_MORE_BEEHIVES_CONFIG)"
flower_flower_forest: "Feature.FLOWER.withConfiguration(DefaultBiomeFeatures.FOREST_FLOWER_CONFIG)"
flower_meadow: "Feature.FLOWER.withConfiguration(DefaultBiomeFeatures.DEFAULT_FLOWER_CONFIG)"
flower_plain: "Feature.FLOWER.withConfiguration(DefaultBiomeFeatures.PLAINS_FLOWER_CONFIG)"
flower_swamp: "Feature.FLOWER.withConfiguration(DefaultBiomeFeatures.BLUE_ORCHID_CONFIG)"
forest_flowers: "Feature.FLOWER.withConfiguration(DefaultBiomeFeatures.FOREST_FLOWER_CONFIG)"
forest_rock: "Feature.FOREST_ROCK.withConfiguration(new BlockBlobConfig(Blocks.MOSSY_COBBLESTONE.getDefaultState(), 0))"
fossil_coal: "Feature.FOSSIL.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
fossil_diamonds: "Feature.FOSSIL.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
freeze_top_layer: "Feature.FREEZE_TOP_LAYER.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
glowstone_extra: "Feature.GLOWSTONE_BLOB.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
huge_brown_mushroom: "Feature.HUGE_BROWN_MUSHROOM.withConfiguration(DefaultBiomeFeatures.BIG_BROWN_MUSHROOM)"
huge_red_mushroom: "Feature.HUGE_RED_MUSHROOM.withConfiguration(DefaultBiomeFeatures.BIG_RED_MUSHROOM)"
ice_patch: "Feature.ICE_PATCH.withConfiguration(new FeatureRadiusConfig(2))"
ice_spike: "Feature.ICE_SPIKE.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
iceberg_blue: "Feature.ICEBERG.withConfiguration(new BlockStateFeatureConfig(Blocks.BLUE_ICE.getDefaultState()))"
iceberg_packed: "Feature.ICEBERG.withConfiguration(new BlockStateFeatureConfig(Blocks.PACKED_ICE.getDefaultState()))"
jungle_bush: "Feature.JUNGLE_GROUND_BUSH.withConfiguration(DefaultBiomeFeatures.JUNGLE_GROUND_BUSH_CONFIG)"
jungle_tree: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.JUNGLE_TREE_CONFIG)"
jungle_tree_no_vine: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.JUNGLE_SAPLING_TREE_CONFIG)"
kelp: "Feature.KELP.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
lake_lava: "Feature.LAKE.withConfiguration(new BlockStateFeatureConfig(Blocks.LAVA.getDefaultState()))"
meadow_trees: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.OAK_TREE_CONFIG)"
mega_jungle_tree: "Feature.MEGA_JUNGLE_TREE.withConfiguration(DefaultBiomeFeatures.MEGA_JUNGLE_TREE_CONFIG)"
mega_pine: "Feature.MEGA_SPRUCE_TREE.withConfiguration(DefaultBiomeFeatures.MEGA_PINE_TREE_CONFIG)"
mega_spruce: "Feature.MEGA_SPRUCE_TREE.withConfiguration(DefaultBiomeFeatures.MEGA_SPRUCE_TREE_CONFIG)"
monster_room: "Feature.MONSTER_ROOM.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
oak: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.OAK_TREE_CONFIG)"
oak_bees_0002: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.field_230132_o_)"
oak_bees_002: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.field_230133_p_)"
oak_bees_005: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.OAK_TREE_WITH_MORE_BEEHIVES_CONFIG)"
ore_andesite: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.ANDESITE.getDefaultState(), 33))"
ore_coal: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.COAL_ORE.getDefaultState(), 17))"
ore_coal_buried: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.COAL_ORE.getDefaultState(), 17))"
ore_diamond_buried: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIAMOND_ORE.getDefaultState(), 8))"
ore_diamond_large: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIAMOND_ORE.getDefaultState(), 8))"
ore_diamond_medium: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIAMOND_ORE.getDefaultState(), 8))"
ore_diamond_small: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIAMOND_ORE.getDefaultState(), 8))"
ore_diorite: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIORITE.getDefaultState(), 33))"
ore_dirt: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIRT.getDefaultState(), 33))"
ore_emerald: "Feature.EMERALD_ORE.withConfiguration(new ReplaceBlockConfig(DefaultBiomeFeatures.STONE, Blocks.EMERALD_ORE.getDefaultState()))"
ore_gold: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GOLD_ORE.getDefaultState(), 9))"
ore_gold_buried: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GOLD_ORE.getDefaultState(), 9))"
ore_granite: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GRANITE.getDefaultState(), 33))"
ore_gravel: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GRAVEL.getDefaultState(), 33))"
ore_gravel_nether: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GRAVEL.getDefaultState(), 33))"
ore_infested: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.INFESTED_STONE.getDefaultState(), 9))"
ore_iron: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.IRON_ORE.getDefaultState(), 9))"
ore_iron_small: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.IRON_ORE.getDefaultState(), 9))"
ore_lapis: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.LAPIS_ORE.getDefaultState(), 7))"
ore_lapis_buried: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.LAPIS_ORE.getDefaultState(), 7))"
ore_magma: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NETHERRACK, Blocks.MAGMA_BLOCK.getDefaultState(), 33))"
ore_quartz: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NETHERRACK, Blocks.NETHER_QUARTZ_ORE.getDefaultState(), 14))"
ore_redstone: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.REDSTONE_ORE.getDefaultState(), 8))"
ore_soul_sand: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NETHERRACK, Blocks.SOUL_SAND.getDefaultState(), 33))"
patch_berry_bush: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.SWEET_BERRY_BUSH_CONFIG)"
patch_brown_mushroom: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.BROWN_MUSHROOM_CONFIG)"
patch_cactus: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.CACTUS_CONFIG)"
patch_dead_bush: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.DEAD_BUSH_CONFIG)"
patch_fire: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.NETHER_FIRE_CONFIG)"
patch_grass: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.GRASS_CONFIG)"
patch_grass_jungle: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.LUSH_GRASS_CONFIG).withPlacement(Placement.COUNT_HEIGHTMAP_DOUBLE.configure(new FrequencyConfig(25)))"
patch_large_fern: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.LARGE_FERN_CONFIG)"
patch_melon: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.MELON_PATCH_CONFIG)"
patch_pumpkin: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.PUMPKIN_PATCH_CONFIG)"
patch_red_mushroom: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.RED_MUSHROOM_CONFIG)"
patch_sugar_cane: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.SUGAR_CANE_CONFIG)"
patch_sunflower: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.SUNFLOWER_CONFIG)"
patch_taiga_grass: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.TAIGA_GRASS_CONFIG).withPlacement(Placement.COUNT_HEIGHTMAP_DOUBLE.configure(new FrequencyConfig(7)))"
patch_tall_grass: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.TALL_GRASS_CONFIG)"
patch_waterlily: "Feature.RANDOM_PATCH.withConfiguration(DefaultBiomeFeatures.LILY_PAD_CONFIG)"
pile_hay: "Feature.BLOCK_PILE.withConfiguration(DefaultBiomeFeatures.HAY_PILE_CONFIG)"
pile_ice: "Feature.BLOCK_PILE.withConfiguration(DefaultBiomeFeatures.BLUE_ICE_PILE_CONFIG)"
pile_melon: "Feature.BLOCK_PILE.withConfiguration(DefaultBiomeFeatures.MELON_PILE_CONFIG)"
pile_pumpkin: "Feature.BLOCK_PILE.withConfiguration(DefaultBiomeFeatures.PUMPKIN_PILE_CONFIG)"
pile_snow: "Feature.BLOCK_PILE.withConfiguration(DefaultBiomeFeatures.SNOW_PILE_CONFIG)"
pine: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.PINE_TREE_CONFIG)"
sea_pickle: "Feature.SEA_PICKLE.withConfiguration(new CountConfig(20))"
seagrass_mid: "Feature.SEAGRASS.withConfiguration(new SeaGrassConfig(80, 0.8D))"
seagrass_short: "Feature.SEAGRASS.withConfiguration(new SeaGrassConfig(80, 0.3D))"
seagrass_slightly_less_short: "Feature.SEAGRASS.withConfiguration(new SeaGrassConfig(32, 0.3D))"
seagrass_tall: "Feature.SEAGRASS.withConfiguration(new SeaGrassConfig(48, 0.3D))"
spring_lava_frozen: "Feature.SPRING_FEATURE.withConfiguration(DefaultBiomeFeatures.LAVA_SPRING_CONFIG).withPlacement(Placement.COUNT_VERY_BIASED_RANGE.configure(new CountRangeConfig(20, 8, 16, 256)))"
spring_lava_nether: "Feature.SPRING_FEATURE.withConfiguration(DefaultBiomeFeatures.NETHER_SPRING_CONFIG).withPlacement(Placement.COUNT_VERY_BIASED_RANGE.configure(new CountRangeConfig(20, 8, 16, 256)))"
spring_lava_overworld: "Feature.SPRING_FEATURE.withConfiguration(DefaultBiomeFeatures.LAVA_SPRING_CONFIG).withPlacement(Placement.COUNT_VERY_BIASED_RANGE.configure(new CountRangeConfig(20, 8, 16, 256)))"
spring_nether_closed: "Feature.SPRING_FEATURE.withConfiguration(DefaultBiomeFeatures.ENCLOSED_NETHER_SPRING_CONFIG).withPlacement(Placement.COUNT_VERY_BIASED_RANGE.configure(new CountRangeConfig(20, 8, 16, 256)))"
spring_nether_open: "Feature.SPRING_FEATURE.withConfiguration(DefaultBiomeFeatures.NETHER_SPRING_CONFIG).withPlacement(Placement.COUNT_VERY_BIASED_RANGE.configure(new CountRangeConfig(20, 8, 16, 256)))"
spring_water: "Feature.SPRING_FEATURE.withConfiguration(DefaultBiomeFeatures.WATER_SPRING_CONFIG).withPlacement(Placement.COUNT_BIASED_RANGE.configure(new CountRangeConfig(50, 8, 8, 256)))"
spruce: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.SPRUCE_TREE_CONFIG)"
super_birch_bees: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.field_230130_i_)"
super_birch_bees_0002: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.field_230130_i_)"
swamp_oak: "Feature.NORMAL_TREE.withConfiguration(DefaultBiomeFeatures.SWAMP_TREE_CONFIG)"
underwater_magma: "Feature.ORE.withConfiguration(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NETHERRACK, Blocks.MAGMA_BLOCK.getDefaultState(), 33))"
vines: "Feature.VINES.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"
void_start_platform: "Feature.VOID_START_PLATFORM.withConfiguration(IFeatureConfig.NO_FEATURE_CONFIG)"