_mcreator_map_template: "@NAMEFeature()"
_default: "TreeFeature(NoFeatureConfig::deserialize, false)"
acacia: "SavannaTreeFeature(NoFeatureConfig::deserialize, false)"
bamboo_no_podzol: "BambooFeature(ProbabilityConfig::deserialize)"
bamboo_some_podzol: "BambooFeature(new ProbabilityConfig(0.2F))"
birch: "BirchTreeFeature(NoFeatureConfig::deserialize, false, false)"
birch_tall: "BirchTreeFeature(NoFeatureConfig::deserialize, false, true)"
blue_ice: "BlueIceFeature(NoFeatureConfig::deserialize)"
bonus_chest: "BonusChestFeature(NoFeatureConfig::deserialize)"
chorus_plant: "ChorusPlantFeature(NoFeatureConfig::deserialize)"
dark_oak: "DarkOakTreeFeature(NoFeatureConfig::deserialize, false)"
desert_well: "DesertWellsFeature(NoFeatureConfig::deserialize)"
disk_clay: "SphereReplaceFeature(new SphereReplaceConfig(Blocks.CLAY.getDefaultState(), 4, 1, Lists.newArrayList(Blocks.DIRT.getDefaultState(), Blocks.CLAY.getDefaultState())))"
disk_gravel: "SphereReplaceFeature(new SphereReplaceConfig(Blocks.GRAVEL.getDefaultState(), 6, 2, Lists.newArrayList(Blocks.DIRT.getDefaultState(), Blocks.GRASS_BLOCK.getDefaultState())))"
disk_sand: "SphereReplaceFeature(new SphereReplaceConfig(Blocks.SAND.getDefaultState(), 7, 2, Lists.newArrayList(Blocks.DIRT.getDefaultState(), Blocks.GRASS_BLOCK.getDefaultState())))"
end_gateway_delayed: "EndGatewayFeature(EndGatewayConfig::deserialize)"
end_gateway_return: "EndGatewayFeature(EndGatewayConfig.func_214702_a(EndDimension.SPAWN, true))"
end_island: "EndIslandFeature(NoFeatureConfig::deserialize)"
end_spike: "EndSpikeFeature(new EndSpikeFeatureConfig(false, ImmutableList.of(), null))"
fancy_oak: "BigTreeFeature(NoFeatureConfig::deserialize, false)"
flower_default: "DefaultFlowersFeature(NoFeatureConfig::deserialize)"
flower_flower_forest: "ForestFlowersFeature(NoFeatureConfig::deserialize)"
flower_meadow: "PlainsFlowersFeature(NoFeatureConfig::deserialize)"
flower_plain: "PlainsFlowersFeature(NoFeatureConfig::deserialize)"
flower_swamp: "SwampFlowersFeature(NoFeatureConfig::deserialize)"
forest_flowers: "GeneralForestFlowerFeature(NoFeatureConfig::deserialize)"
forest_rock: "BlockBlobFeature(new BlockBlobConfig(Blocks.MOSSY_COBBLESTONE.getDefaultState(), 0))"
fossil_coal: "FossilsFeature(NoFeatureConfig::deserialize)"
fossil_diamonds: "FossilsFeature(NoFeatureConfig::deserialize)"
freeze_top_layer: "IceAndSnowFeature(NoFeatureConfig::deserialize)"
glowstone_extra: "GlowstoneBlobFeature(NoFeatureConfig::deserialize)"
huge_brown_mushroom: "BigBrownMushroomFeature(BigMushroomFeatureConfig::deserialize)"
huge_red_mushroom: "BigRedMushroomFeature(BigMushroomFeatureConfig::deserialize)"
ice_patch: "IcePathFeature(new FeatureRadiusConfig(2))"
ice_spike: "IceSpikeFeature(NoFeatureConfig::deserialize)"
iceberg_blue: "IcebergFeature(new IcebergConfig(Blocks.BLUE_ICE.getDefaultState()))"
iceberg_packed: "IcebergFeature(new IcebergConfig(Blocks.PACKED_ICE.getDefaultState()))"
jungle_bush: "ShrubFeature(NoFeatureConfig::deserialize, Blocks.JUNGLE_LOG.getDefaultState(), Blocks.OAK_LEAVES.getDefaultState())"
jungle_tree: "JungleTreeFeature(NoFeatureConfig::deserialize, false, 4, Blocks.JUNGLE_LOG.getDefaultState(), Blocks.JUNGLE_LEAVES.getDefaultState(), true)"
jungle_tree_no_vine: "JungleTreeFeature(NoFeatureConfig::deserialize, false, 4, Blocks.JUNGLE_LOG.getDefaultState(), Blocks.JUNGLE_LEAVES.getDefaultState(), false)"
kelp: "KelpFeature(NoFeatureConfig::deserialize)"
lake_lava: "LakesFeature(LakesConfig::deserialize)"
meadow_trees: "TreeFeature(NoFeatureConfig::deserialize, false)"
mega_jungle_tree: "MegaJungleFeature(NoFeatureConfig::deserialize, false, 10, 20, Blocks.JUNGLE_LOG.getDefaultState(), Blocks.JUNGLE_LEAVES.getDefaultState())"
mega_pine: "MegaPineTree(NoFeatureConfig::deserialize, false, false)"
mega_spruce: "MegaPineTree(NoFeatureConfig::deserialize, false, true)"
monster_room: "DungeonsFeature(NoFeatureConfig::deserialize)"
oak: "TreeFeature(NoFeatureConfig::deserialize, false)"
ore_andesite: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.ANDESITE.getDefaultState(), 33))"
ore_coal: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.COAL_ORE.getDefaultState(), 17))"
ore_coal_buried: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.COAL_ORE.getDefaultState(), 17))"
ore_diamond_buried: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIAMOND_ORE.getDefaultState(), 8))"
ore_diamond_large: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIAMOND_ORE.getDefaultState(), 8))"
ore_diamond_medium: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIAMOND_ORE.getDefaultState(), 8))"
ore_diamond_small: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIAMOND_ORE.getDefaultState(), 8))"
ore_diorite: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIORITE.getDefaultState(), 33))"
ore_dirt: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.DIRT.getDefaultState(), 33))"
ore_emerald: "ReplaceBlockFeature(new ReplaceBlockConfig(Blocks.STONE.getDefaultState(), Blocks.EMERALD_ORE.getDefaultState()))"
ore_gold: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GOLD_ORE.getDefaultState(), 9))"
ore_gold_buried: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GOLD_ORE.getDefaultState(), 9))"
ore_granite: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GRANITE.getDefaultState(), 33))"
ore_gravel: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.GRAVEL.getDefaultState(), 33))"
ore_gravel_nether: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NETHERRACK, Blocks.GRAVEL.getDefaultState(), 33))"
ore_infested: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.INFESTED_STONE.getDefaultState(), 9))"
ore_iron: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.IRON_ORE.getDefaultState(), 9))"
ore_iron_small: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.IRON_ORE.getDefaultState(), 9))"
ore_lapis: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.LAPIS_ORE.getDefaultState(), 7))"
ore_lapis_buried: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.LAPIS_ORE.getDefaultState(), 7))"
ore_magma: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NETHERRACK, Blocks.MAGMA_BLOCK.getDefaultState(), 33))"
ore_quartz: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NETHERRACK, Blocks.NETHER_QUARTZ_ORE.getDefaultState(), 14))"
ore_redstone: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.REDSTONE_ORE.getDefaultState(), 8))"
ore_soul_sand: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NETHERRACK, Blocks.SOUL_SAND.getDefaultState(), 33))"
patch_berry_bush: "ScatteredPlantFeature(NoFeatureConfig::deserialize, Blocks.SWEET_BERRY_BUSH.getDefaultState().with(SweetBerryBushBlock.AGE, Integer.valueOf(3)))"
patch_brown_mushroom: "BushFeature(new BushConfig(Blocks.BROWN_MUSHROOM.getDefaultState()))"
patch_cactus: "CactusFeature(NoFeatureConfig::deserialize)"
patch_dead_bush: "DeadBushFeature(NoFeatureConfig::deserialize)"
patch_fire: "FireFeature(NoFeatureConfig::deserialize)"
patch_grass: "GrassFeature(new GrassFeatureConfig(Blocks.GRASS.getDefaultState()))"
patch_grass_jungle: "JungleGrassFeature(NoFeatureConfig::deserialize)"
patch_large_fern: "DoublePlantFeature(new DoublePlantConfig(Blocks.LARGE_FERN.getDefaultState()))"
patch_melon: "MelonFeature(NoFeatureConfig::deserialize)"
patch_pumpkin: "ScatteredPlantFeature(NoFeatureConfig::deserialize, Blocks.PUMPKIN.getDefaultState())"
patch_red_mushroom: "BushFeature(new BushConfig(Blocks.RED_MUSHROOM.getDefaultState()))"
patch_sugar_cane: "ReedFeature(NoFeatureConfig::deserialize)"
patch_sunflower: "DoublePlantFeature(new DoublePlantConfig(Blocks.SUNFLOWER.getDefaultState()))"
patch_taiga_grass: "TaigaGrassFeature(NoFeatureConfig::deserialize)"
patch_tall_grass: "DoublePlantFeature(new DoublePlantConfig(Blocks.TALL_GRASS.getDefaultState()))"
patch_waterlily: "WaterlilyFeature(NoFeatureConfig::deserialize)"
pile_hay: "HayBlockPileFeature(NoFeatureConfig::deserialize)"
pile_ice: "IceBlockPileFeature(NoFeatureConfig::deserialize)"
pile_melon: "MelonBlockPileFeature(NoFeatureConfig::deserialize)"
pile_pumpkin: "PumpkinBlockPileFeature(NoFeatureConfig::deserialize)"
pile_snow: "SnowBlockPileFeature(NoFeatureConfig::deserialize)"
pine: "PointyTaigaTreeFeature(NoFeatureConfig::deserialize)"
sea_pickle: "SeaPickleFeature(new CountConfig(20))"
seagrass_mid: "SeaGrassFeature(new SeaGrassConfig(80, 0.8D))"
seagrass_short: "SeaGrassFeature(new SeaGrassConfig(80, 0.3D))"
seagrass_slightly_less_short: "SeaGrassFeature(new SeaGrassConfig(32, 0.3D))"
seagrass_tall: "SeaGrassFeature(new SeaGrassConfig(48, 0.3D))"
spring_lava_frozen: "SpringFeature(new LiquidsConfig(Fluids.LAVA.getDefaultState()))"
spring_lava_nether: "NetherSpringFeature(new HellLavaConfig(false))"
spring_lava_overworld: "SpringFeature(new LiquidsConfig(Fluids.LAVA.getDefaultState()))"
spring_nether_closed: "NetherSpringFeature(new HellLavaConfig(false))"
spring_nether_open: "NetherSpringFeature(new HellLavaConfig(true))"
spring_water: "SpringFeature(LiquidsConfig::deserialize)"
spruce: "TallTaigaTreeFeature(NoFeatureConfig::deserialize, false)"
swamp_oak: "SwampTreeFeature(NoFeatureConfig::deserialize)"
underwater_magma: "OreFeature(new OreFeatureConfig(OreFeatureConfig.FillerBlockType.NATURAL_STONE, Blocks.MAGMA_BLOCK.getDefaultState(), 33))"
vines: "VinesFeature(NoFeatureConfig::deserialize)"
void_start_platform: "VoidStartPlatformFeature(NoFeatureConfig::deserialize)"